"""empty message

Revision ID: 13f83eced48
Revises: 1c3b4b9bdebe
Create Date: 2015-01-23 16:43:39.167930

"""

# revision identifiers, used by Alembic.
revision = '13f83eced48'
down_revision = '1c3b4b9bdebe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
