"""empty message

Revision ID: 14f9d9a18c04
Revises: 32c208e7f09
Create Date: 2015-02-24 16:28:18.185675

"""

# revision identifiers, used by Alembic.
revision = '14f9d9a18c04'
down_revision = '32c208e7f09'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('concat', sa.String(), nullable=True))
    op.add_column('releases', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('releases', sa.Column('decision', sa.String(), nullable=True))
    op.add_column('releases', sa.Column('dossier', sa.String(), nullable=True))
    op.add_column('releases', sa.Column('supplier', sa.String(), nullable=True))
    op.add_column('releases', sa.Column('supplier_slug', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('last_retrieve', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'last_retrieve')
    op.drop_column('releases', 'supplier_slug')
    op.drop_column('releases', 'supplier')
    op.drop_column('releases', 'dossier')
    op.drop_column('releases', 'decision')
    op.drop_column('releases', 'date')
    op.drop_column('releases', 'concat')
    ### end Alembic commands ###
