"""empty message

Revision ID: 1973b709df81
Revises: 1457566837a1
Create Date: 2015-02-13 14:33:38.014130

"""

# revision identifiers, used by Alembic.
revision = '1973b709df81'
down_revision = '1457566837a1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('awards')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards',
    sa.Column('awardID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('awardDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('awardValue', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('json', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.Column('release_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['release_id'], [u'releases.ocid'], name=u'awards_release_id_fkey'),
    sa.PrimaryKeyConstraint('awardID', name=u'awards_pkey')
    )
    ### end Alembic commands ###
