"""empty message

Revision ID: 1c3b4b9bdebe
Revises: 49c4c8793f13
Create Date: 2015-01-23 16:30:43.698532

"""

# revision identifiers, used by Alembic.
revision = '1c3b4b9bdebe'
down_revision = '49c4c8793f13'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('awards', 'description')
    op.add_column('releases', sa.Column('description', sa.String(), nullable=True))
    op.add_column('releases', sa.Column('value', sa.Integer(), nullable=True))
    op.drop_column('releases', 'decription')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('decription', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('releases', 'value')
    op.drop_column('releases', 'description')
    op.add_column('awards', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
