"""empty message

Revision ID: 1ef7ffaf88d9
Revises: 24629378c350
Create Date: 2015-02-25 10:33:26.407851

"""

# revision identifiers, used by Alembic.
revision = '1ef7ffaf88d9'
down_revision = '24629378c350'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('activities', postgresql.ARRAY(sa.String()), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releases', 'activities')
    ### end Alembic commands ###
