"""empty message

Revision ID: 2732661b799a
Revises: 41894a3f354d
Create Date: 2015-03-29 22:01:53.754391

"""

# revision identifiers, used by Alembic.
revision = '2732661b799a'
down_revision = '41894a3f354d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_stats')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('datetime', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('args', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.Column('referrer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'daily_stats_pkey')
    )
    ### end Alembic commands ###
