"""empty message

Revision ID: 2dbc1026957d
Revises: None
Create Date: 2015-01-17 14:19:26.615417

"""

# revision identifiers, used by Alembic.
revision = '2dbc1026957d'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releases',
    sa.Column('ocid', sa.String(), nullable=False),
    sa.Column('langage', sa.String(), nullable=True),
    sa.Column('json', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('ocid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('releases')
    ### end Alembic commands ###
