"""empty message

Revision ID: 3148ed813ae8
Revises: None
Create Date: 2015-02-20 10:34:35.559337

"""

# revision identifiers, used by Alembic.
revision = '3148ed813ae8'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('buyer_uid', sa.Integer(), nullable=False),
    sa.Column('buyer_name', sa.String(), nullable=True),
    sa.Column('json', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('buyer_uid')
    )
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocid', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('json', postgresql.JSON(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.buyer_uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('releases')
    op.drop_table('buyers')
    ### end Alembic commands ###
