"""empty message

Revision ID: 32829c2b1743
Revises: 469da493e3a3
Create Date: 2015-03-23 15:28:59.506623

"""

# revision identifiers, used by Alembic.
revision = '32829c2b1743'
down_revision = '469da493e3a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'releases', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'releases', 'suppliers', ['supplier_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'releases', type_='foreignkey')
    op.drop_column(u'releases', 'supplier_id')
    op.drop_table('suppliers')
    ### end Alembic commands ###
