"""empty message

Revision ID: 32c208e7f09
Revises: 3ae36218f1bc
Create Date: 2015-02-20 11:33:50.305176

"""

# revision identifiers, used by Alembic.
revision = '32c208e7f09'
down_revision = '3ae36218f1bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
