"""empty message

Revision ID: 35b0e61d7f67
Revises: 51f60ab0689b
Create Date: 2015-01-18 10:05:29.909623

"""

# revision identifiers, used by Alembic.
revision = '35b0e61d7f67'
down_revision = '51f60ab0689b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
