"""empty message

Revision ID: 37d3cd506cb8
Revises: 13f83eced48
Create Date: 2015-02-13 10:01:22.835777

"""

# revision identifiers, used by Alembic.
revision = '37d3cd506cb8'
down_revision = '13f83eced48'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('releases')
    op.drop_table('awards')
    op.drop_table('buyers')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('buyer_uid', sa.INTEGER(), server_default=sa.text(u"nextval('buyers_buyer_uid_seq'::regclass)"), nullable=False),
    sa.Column('buyer_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('json', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('buyer_uid', name=u'buyers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('awards',
    sa.Column('awardID', sa.INTEGER(), server_default=sa.text(u'nextval(\'"awards_awardID_seq"\'::regclass)'), nullable=False),
    sa.Column('awardDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('awardValue', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('json', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.Column('release_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['release_id'], [u'releases.ocid'], name=u'awards_release_id_fkey'),
    sa.PrimaryKeyConstraint('awardID', name=u'awards_pkey')
    )
    op.create_table('releases',
    sa.Column('ocid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('json', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('buyer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], [u'buyers.buyer_uid'], name=u'releases_buyer_id_fkey'),
    sa.PrimaryKeyConstraint('ocid', name=u'releases_pkey')
    )
    ### end Alembic commands ###
