"""empty message

Revision ID: 3875305d4c29
Revises: 4401a16c60fa
Create Date: 2015-03-26 19:20:52.944344

"""

# revision identifiers, used by Alembic.
revision = '3875305d4c29'
down_revision = '4401a16c60fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
