"""empty message

Revision ID: 38acd2fec579
Revises: 98f0ed0ac17
Create Date: 2015-03-26 20:54:31.518881

"""

# revision identifiers, used by Alembic.
revision = '38acd2fec579'
down_revision = '98f0ed0ac17'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('procuring_entity_slug', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releases', 'procuring_entity_slug')
    ### end Alembic commands ###
