"""empty message

Revision ID: 3ae36218f1bc
Revises: d1b8e014c97
Create Date: 2015-02-20 11:02:36.150404

"""

# revision identifiers, used by Alembic.
revision = '3ae36218f1bc'
down_revision = 'd1b8e014c97'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('last_update', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'last_update')
    ### end Alembic commands ###
