"""empty message

Revision ID: 3b43ee44d982
Revises: 4926b1afe611
Create Date: 2015-01-21 20:25:08.859125

"""

# revision identifiers, used by Alembic.
revision = '3b43ee44d982'
down_revision = '4926b1afe611'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', sa.Column('description', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('awards', 'description')
    ### end Alembic commands ###
