"""empty message

Revision ID: 3dab0005f78c
Revises: 32829c2b1743
Create Date: 2015-03-24 10:57:05.309278

"""

# revision identifiers, used by Alembic.
revision = '3dab0005f78c'
down_revision = '32829c2b1743'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releases', 'supplier')
    op.drop_column('releases', 'supplier_slug')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('supplier_slug', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('releases', sa.Column('supplier', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
