"""empty message

Revision ID: 41894a3f354d
Revises: 563b0308900f
Create Date: 2015-03-29 21:53:34.429435

"""

# revision identifiers, used by Alembic.
revision = '41894a3f354d'
down_revision = '563b0308900f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('total_counts', sa.Integer(), nullable=True),
    sa.Column('referrers', postgresql.JSON(), nullable=True),
    sa.Column('counts_app', sa.Integer(), nullable=True),
    sa.Column('path', postgresql.JSON(), nullable=True),
    sa.Column('args', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    ### end Alembic commands ###
