"""empty message

Revision ID: 4401a16c60fa
Revises: 3dab0005f78c
Create Date: 2015-03-24 11:34:51.096560

"""

# revision identifiers, used by Alembic.
revision = '4401a16c60fa'
down_revision = '3dab0005f78c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_releases_date'), 'releases', ['date'], unique=False)
    op.create_index(op.f('ix_releases_type'), 'releases', ['type'], unique=False)
    op.create_index(op.f('ix_releases_value'), 'releases', ['value'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_releases_value'), table_name='releases')
    op.drop_index(op.f('ix_releases_type'), table_name='releases')
    op.drop_index(op.f('ix_releases_date'), table_name='releases')
    ### end Alembic commands ###
