"""empty message

Revision ID: 469da493e3a3
Revises: 33fa645dbb31
Create Date: 2015-03-22 17:46:53.268350

"""

# revision identifiers, used by Alembic.
revision = '469da493e3a3'
down_revision = '33fa645dbb31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('type', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releases', 'type')
    ### end Alembic commands ###
