"""empty message

Revision ID: 4926b1afe611
Revises: 35b0e61d7f67
Create Date: 2015-01-18 10:11:02.553490

"""

# revision identifiers, used by Alembic.
revision = '4926b1afe611'
down_revision = '35b0e61d7f67'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('buyer_uid', sa.Integer(), nullable=False),
    sa.Column('buyer_name', sa.String(), nullable=True),
    sa.Column('json', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('buyer_uid')
    )
    op.drop_table('Buyers')
    op.add_column('releases', sa.Column('buyer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'releases', 'buyers', ['buyer_id'], ['buyer_uid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'releases', type_='foreignkey')
    op.drop_column('releases', 'buyer_id')
    op.create_table('Buyers',
    sa.Column('buyer_uid', sa.INTEGER(), server_default=sa.text(u'nextval(\'"Buyers_buyer_uid_seq"\'::regclass)'), nullable=False),
    sa.Column('buyer_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('json', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('buyer_uid', name=u'Buyers_pkey')
    )
    op.drop_table('buyers')
    ### end Alembic commands ###
