"""empty message

Revision ID: 49c4c8793f13
Revises: 4dd568a56e6b
Create Date: 2015-01-22 22:01:03.468699

"""

# revision identifiers, used by Alembic.
revision = '49c4c8793f13'
down_revision = '4dd568a56e6b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
