"""empty message

Revision ID: 4f6381a5d1ac
Revises: 37d3cd506cb8
Create Date: 2015-02-13 10:27:03.375149

"""

# revision identifiers, used by Alembic.
revision = '4f6381a5d1ac'
down_revision = '37d3cd506cb8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
