"""empty message

Revision ID: 51f60ab0689b
Revises: 2dbc1026957d
Create Date: 2015-01-18 09:40:37.771443

"""

# revision identifiers, used by Alembic.
revision = '51f60ab0689b'
down_revision = '2dbc1026957d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Buyers',
    sa.Column('buyer_uid', sa.Integer(), nullable=False),
    sa.Column('buyer_name', sa.String(), nullable=True),
    sa.Column('json', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('buyer_uid')
    )
    op.create_table('awards',
    sa.Column('awardID', sa.Integer(), nullable=False),
    sa.Column('awardDate', sa.Date(), nullable=True),
    sa.Column('awardValue', sa.Integer(), nullable=True),
    sa.Column('json', postgresql.JSON(), nullable=True),
    sa.Column('release_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.ocid'], ),
    sa.PrimaryKeyConstraint('awardID')
    )
    op.add_column(u'releases', sa.Column('language', sa.String(), nullable=True))
    op.drop_column(u'releases', 'langage')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'releases', sa.Column('langage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column(u'releases', 'language')
    op.drop_table('awards')
    op.drop_table('Buyers')
    ### end Alembic commands ###
