"""empty message

Revision ID: 98f0ed0ac17
Revises: 3875305d4c29
Create Date: 2015-03-26 20:25:33.704746

"""

# revision identifiers, used by Alembic.
revision = '98f0ed0ac17'
down_revision = '3875305d4c29'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('alter table releases alter column activities type text[]')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('alter table releases alter column activities type varchar[]')
    pass
    ### end Alembic commands ###
