"""empty message

Revision ID: d1b8e014c97
Revises: 3148ed813ae8
Create Date: 2015-02-20 10:53:30.661205

"""

# revision identifiers, used by Alembic.
revision = 'd1b8e014c97'
down_revision = '3148ed813ae8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mapper', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'releases', sa.Column('source_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'releases', 'sources', ['source_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'releases', type_='foreignkey')
    op.drop_column(u'releases', 'source_id')
    op.drop_table('sources')
    ### end Alembic commands ###
